name: default
background_color: "#FFFFFF"
box_fill: "#F8F9FA"
box_stroke: "#343A40"
box_stroke_width: 2
border_radius: 6
text_color: "#212529"
font_family: "'Noto Sans JP', Helvetica, Arial, sans-serif"
font_size: 14
annotation_font_size: 12
annotation_color: "#6C757D"
arrow_color: "#495057"
nested_box_fill: "#E9ECEF"
section_header_fill: "#DEE2E6"
metrics:
  cell_width: 10
  cell_height: 20
  padding: 20
